[package]
name = "x_dg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
extension_lib = { path = "../extension_lib" }
serde_json = "1.0.78"
serde = "1.0.136"
serde_derive = "1.0.136"
